# Name of your site (displayed in the header)
name: pirad

# Short bio or description (displayed in the header)
description: stuff I want to write down


theme: jekyll-theme-hacker

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"
